### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by kushwavez** [SaeedHaidar/Nitro-5-an517-51-Hackintosh#10]
Hi! I see you also had hard time fixing your trackpad, I'm glad you fixed it. Could you please share the steps you did there? I'm also having hard time fixing mine. How should I start? I started with VoodoI2C tutorial, but doesn't seem to work, the kexts can't find my I2C device. Therefore I need SSDT for my unique device. I see yours is I2C-TPAD, how you could find it's name? 
And after I did my SSDT, do I just need to put the kexts (VoodoI2C, VoodoI2CHID, VoodoPS2Controller (removed mouse), and the SSDT then that's it?

This is the very last issue on my hack.
I really appreciate any help.

This is my full setup:

Acer Aspire V5-591G-55TU
i5-6300HQ
ELAN0501 is the name of the trackpad
Now I'm using [EMlyDinEsH's SmartTouchpadDriver](https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/) but it's really buggy.

**Comment by smartass08** [comment]
Ya please if you guide us, That would be very good. I have an acer predator helios 300 and having same issues for trackpad

**Comment by kushwavez** [comment]
@smartass08 here what I did so far after I wrote that. I created a DSDT for my notebook, added the Windows 10 patch and the GPI0 enabler [SKL+], restarted the system and opened IOReg, found my trackpad's name TPDE (you can also found that in Windows) and the PIN number 3A. After that I patched the DSDT using these informations following the instructions on VoodooI2C main site, placed the kexts (VoodooI2C and VoodooI2CHID) to OC/Kexts, added them to config.plist and restarted the system. Unfortunately I still have no trackpad working. According to kextstat the kexts are not loaded, just the VoodooGPIO and VoodooI2CServices, no satellite kext. TPDE still recognised in IOReg. I feel that I'm in the finish but I don't know what am I doing wrong. here my debug files: [debug.zip](https://drive.google.com/file/d/1ZNyly9uxCsxuZFP81E_OyVwQwpaWrYGs/view?usp=sharing)

**Comment by lrprawira** [comment]
@vaczi001 @smartass08  
Okay. I finally have my touchpad working on my nitro 5 an515-52. Just in case someone finds this issue and still hasn't gotten it working, here's what I did (using OpenCore):
- You probably need SSDT-GPI0 and SSDT-XOSI both  
- You need to apply `Change _OSI to XOSI` patch to your `config.plist`. You can find it easily in the OC Guide  
- I'm not sure if you need separate VoodooInput.kext but I use it instead of the included ones in VoodooPS2Controller.kext and VoodooI2C.kext. But, **you need all three of them plus VoodooI2CHID.kext** (VoodooI2CELAN would just throw something like `VoodooI2CELANTouchpadDriver::ELAN0504 Invalid Report (0)` and the trackpad itself won't work despite it getting detected inside the preferences.)  
- Don't forget to put everything inside `config.plist` (the SSDT and the kexts) , the order matters for the kexts. You can generate it inside ProperTree. My configuration order *may* work for you too:  
  1. VoodooI2CServices.kext (bundled inside VoodooI2C.kext)  
  2. VoodooI2CGPIO.kext (bundled inside VoodooI2C.kext)  
  3. VoodooInput.kext (If this doesn't work, try to add VoodooInput.kext from other bundles alongside as well)  
  4. VoodooPS2Controller.kext  
  5. VoodooPS2Keyboard.kext (bundled inside VoodooPS2Controller.kext)  
  6. VoodooI2C.kext
  7. VoodooI2CHID.kext

**Comment by Gilgatron** [comment]
> @vaczi001 [@smartass08](https://github.com/smartass08) Okay. I finally have my touchpad working on my nitro 5 an515-52. Just in case someone finds this issue and still hasn't gotten it working, here's what I did (using OpenCore):
> 
>     * You probably need SSDT-GPI0 and SSDT-XOSI both
> 
>     * You need to apply `Change _OSI to XOSI` patch to your `config.plist`. You can find it easily in the OC Guide
> 
>     * I'm not sure if you need separate VoodooInput.kext but I use it instead of the included ones in VoodooPS2Controller.kext and VoodooI2C.kext. But, **you need all three of them plus VoodooI2CHID.kext** (VoodooI2CELAN would just throw something like `VoodooI2CELANTouchpadDriver::ELAN0504 Invalid Report (0)` and the trackpad itself won't work despite it getting detected inside the preferences.)
> 
>     * Don't forget to put everything inside `config.plist` (the SSDT and the kexts) , the order matters for the kexts. You can generate it inside ProperTree. My configuration order _may_ work for you too:
>       
>       1. VoodooI2CServices.kext (bundled inside VoodooI2C.kext)
>       2. VoodooI2CGPIO.kext (bundled inside VoodooI2C.kext)
>       3. VoodooInput.kext (If this doesn't work, try to add VoodooInput.kext from other bundles alongside as well)
>       4. VoodooPS2Controller.kext
>       5. VoodooPS2Keyboard.kext (bundled inside VoodooPS2Controller.kext)
>       6. VoodooI2C.kext
>       7. VoodooI2CHID.kext

brooooooo you mad my day i was very hopeless and you saved me :)
